-- Equipes de manutencao
INSERT INTO EQUIPE_MANUTENCAO (NOME, QTD_INTEGRANTES) VALUES ('Equipe Norte', 5);
INSERT INTO EQUIPE_MANUTENCAO (NOME, QTD_INTEGRANTES) VALUES ('Equipe Sul', 4);
INSERT INTO EQUIPE_MANUTENCAO (NOME, QTD_INTEGRANTES) VALUES ('Equipe Pulverizacao Quimica', 3);

-- Trechos de rodovia (variando nivel de vegetacao para testar)
INSERT INTO TRECHO_RODOVIA (KM_INICIAL, KM_FINAL, NIVEL_VEGETACAO, TIPO_AMBIENTE, POSSUI_SENSOR_IOT)
VALUES (10.0, 15.0, 45.0, 'UMIDO', 'S');

INSERT INTO TRECHO_RODOVIA (KM_INICIAL, KM_FINAL, NIVEL_VEGETACAO, TIPO_AMBIENTE, POSSUI_SENSOR_IOT)
VALUES (15.0, 20.0, 25.0, 'TROPICAL', 'S');

INSERT INTO TRECHO_RODOVIA (KM_INICIAL, KM_FINAL, NIVEL_VEGETACAO, TIPO_AMBIENTE, POSSUI_SENSOR_IOT)
VALUES (20.0, 25.0, 12.0, 'SECO', 'N');

INSERT INTO TRECHO_RODOVIA (KM_INICIAL, KM_FINAL, NIVEL_VEGETACAO, TIPO_AMBIENTE, POSSUI_SENSOR_IOT)
VALUES (25.0, 30.0, 5.0, 'PADRAO', 'N');

INSERT INTO TRECHO_RODOVIA (KM_INICIAL, KM_FINAL, NIVEL_VEGETACAO, TIPO_AMBIENTE, POSSUI_SENSOR_IOT)
VALUES (30.0, 35.0, 41.0, 'TROPICAL', 'S');

-- Intervencoes de exemplo
INSERT INTO INTERVENCAO_OPERACIONAL (DESCRICAO, ID_TRECHO_ALVO, TIPO_INTERVENCAO, TIPO_EQUIPAMENTO)
VALUES ('Rocada mecanizada - trecho critico', 1, 'MECANIZADA', 'Trator roçadeira TR-200');

INSERT INTO INTERVENCAO_OPERACIONAL (DESCRICAO, ID_TRECHO_ALVO, TIPO_INTERVENCAO, NUMERO_PESSOAS)
VALUES ('Rocada manual - trecho em atencao', 2, 'MANUAL', 4);

INSERT INTO INTERVENCAO_OPERACIONAL (DESCRICAO, ID_TRECHO_ALVO, TIPO_INTERVENCAO, PRODUTO_QUIMICO, VOLUME_LITROS)
VALUES ('Pulverizacao - trecho em alerta', 3, 'PULVERIZACAO', 'Herbicida seletivo X1', 12.5);

-- Historico de relatório
INSERT INTO RELATORIO_PRIORIDADE (QT_CRITICO, QT_ATENCAO, QT_ALERTA, QT_NORMAL, RESUMO)
VALUES (2, 1, 1, 1, 'Relatorio inicial de carga de dados de teste');

COMMIT;