
-- Baseada na classe EquipeManutencao (nome, quantidadeIntegrantes)
CREATE TABLE EQUIPE_MANUTENCAO (
    ID_EQUIPE           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME                VARCHAR2(100)   NOT NULL,
    QTD_INTEGRANTES     NUMBER(5)       NOT NULL
);

-- Baseada na classe TrechoRodovia (implementa MonitoravelViaIoT)
CREATE TABLE TRECHO_RODOVIA (
    ID_TRECHO           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    KM_INICIAL          NUMBER(10,2)    NOT NULL,
    KM_FINAL            NUMBER(10,2)    NOT NULL,
    NIVEL_VEGETACAO     NUMBER(10,2)    NOT NULL,
    TIPO_AMBIENTE       VARCHAR2(20)    NOT NULL,
    POSSUI_SENSOR_IOT   CHAR(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT CK_TIPO_AMBIENTE CHECK (TIPO_AMBIENTE IN ('UMIDO','SECO','TROPICAL','PADRAO')),
    CONSTRAINT CK_SENSOR_IOT CHECK (POSSUI_SENSOR_IOT IN ('S','N')),
    CONSTRAINT CK_KM_VALIDO CHECK (KM_FINAL > KM_INICIAL)
);


-- Baseada na classe abstrata IntervencaoOperacional e nas  subclasses RocadaMecanizada, RocadaManual, Pulverizacao.
CREATE TABLE INTERVENCAO_OPERACIONAL (
    ID_INTERVENCAO      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DESCRICAO           VARCHAR2(200)   NOT NULL,
    ID_TRECHO_ALVO      NUMBER          NOT NULL,
    TIPO_INTERVENCAO    VARCHAR2(20)    NOT NULL,

    -- especificos de RocadaMecanizada
    TIPO_EQUIPAMENTO    VARCHAR2(100),

    -- Especifico de RocadaManual
    NUMERO_PESSOAS      NUMBER(5),

    -- Especificos de Pulverizacao
    PRODUTO_QUIMICO     VARCHAR2(100),
    VOLUME_LITROS       NUMBER(10,2),

    DATA_INTERVENCAO    DATE DEFAULT SYSDATE NOT NULL,

    CONSTRAINT FK_INTERVENCAO_TRECHO FOREIGN KEY (ID_TRECHO_ALVO)
        REFERENCES TRECHO_RODOVIA (ID_TRECHO),
    CONSTRAINT CK_TIPO_INTERVENCAO CHECK (TIPO_INTERVENCAO IN ('MECANIZADA','MANUAL','PULVERIZACAO'))
);

-- Historico gerado pelo GeradorRelatorio / MotorPrioridade
-- Classificacao usada pelo MotorPrioridade:
--   >= 40 cm -> CRITICO   | >= 20 cm -> ATENCAO
--   >= 10 cm -> ALERTA    | <  10 cm -> NORMAL

CREATE TABLE RELATORIO_PRIORIDADE (
    ID_RELATORIO        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    QT_CRITICO           NUMBER(6) DEFAULT 0 NOT NULL,
    QT_ATENCAO           NUMBER(6) DEFAULT 0 NOT NULL,
    QT_ALERTA            NUMBER(6) DEFAULT 0 NOT NULL,
    QT_NORMAL            NUMBER(6) DEFAULT 0 NOT NULL,
    RESUMO               VARCHAR2(4000),
    DATA_GERACAO         DATE DEFAULT SYSDATE NOT NULL
);
